local A = require("alf.elements.a")
local Article = require("alf.elements.article")
local Aside = require("alf.elements.aside")
local Audio = require("alf.elements.audio")
local Blockquote = require("alf.elements.blockquote")
local Body = require("alf.elements.body")
local Br = require("alf.elements.br")
local Button = require("alf.elements.button")
local Caption = require("alf.elements.caption")
local Code = require("alf.elements.code")
local Div = require("alf.elements.div")
local Em = require("alf.elements.em")
local Figcaption = require("alf.elements.figcaption")
local Figure = require("alf.elements.figure")
local Footer = require("alf.elements.footer")
local Form = require("alf.elements.form")
local H1 = require("alf.elements.h1")
local H2 = require("alf.elements.h2")
local H3 = require("alf.elements.h3")
local H4 = require("alf.elements.h4")
local H5 = require("alf.elements.h5")
local H6 = require("alf.elements.h6")
local Head = require("alf.elements.head")
local Header = require("alf.elements.header")
local Hr = require("alf.elements.hr")
local Html = require("alf.elements.html")
local Img = require("alf.elements.img")
local Input = require("alf.elements.input")
local Ins = require("alf.elements.ins")
local Label = require("alf.elements.label")
local Li = require("alf.elements.li")
local Link = require("alf.elements.link")
local Main = require("alf.elements.main")
local Mark = require("alf.elements.mark")
local Meta = require("alf.elements.meta")
local Nav = require("alf.elements.nav")
local Ol = require("alf.elements.ol")
local Option = require("alf.elements.option")
local P = require("alf.elements.p")
local Pre = require("alf.elements.pre")
local Script = require("alf.elements.script")
local Section = require("alf.elements.section")
local Select = require("alf.elements.select")
local Span = require("alf.elements.span")
local Strong = require("alf.elements.strong")
local Table = require("alf.elements.table")
local Tbody = require("alf.elements.tbody")
local Td = require("alf.elements.td")
local Textarea = require("alf.elements.textarea")
local Th = require("alf.elements.th")
local Thead = require("alf.elements.thead")
local Title = require("alf.elements.title")
local Tr = require("alf.elements.tr")
local Ul = require("alf.elements.ul")
local Video = require("alf.elements.video")


describe("HTML elements", function()
    describe("Div", function()
        it("should render an empty div", function()
            local div = Div()
            assert.are.equal("<div></div>", div:render())
        end)

        it("should render a div with content", function()
            local div = Div(nil, { "Hello, Div!" })
            assert.are.equal("<div>Hello, Div!</div>", div:render())
        end)

        it("should render a div with attributes", function()
            local div = Div():addAttribute("class='container'")
            assert.are.equal("<div class='container'></div>", div:render())
        end)

        it("should render a div with children", function()
            local p = P(nil, { "Child paragraph" })
            local div = Div(nil, { p })
            assert.are.equal("<div><p>Child paragraph</p></div>", div:render())
        end)

        it("should render nested divs", function()
            local innerDiv = Div(nil, { "Inner content" })
            local outerDiv = Div(nil, { "Outer content", innerDiv })
            assert.are.equal("<div>Outer content<div>Inner content</div></div>", outerDiv:render())
        end)
    end)

    describe("P", function()
        it("should render an empty paragraph", function()
            local p = P()
            assert.are.equal("<p></p>", p:render())
        end)

        it("should render a paragraph with text content", function()
            local p = P(nil, { "This is a paragraph." })
            assert.are.equal("<p>This is a paragraph.</p>", p:render())
        end)

        it("should render a paragraph with attributes", function()
            local p = P():addAttribute("class='text-red'")
            assert.are.equal("<p class='text-red'></p>", p:render())
        end)

        it("should render a paragraph with mixed content", function()
            local strong = Strong(nil, { "important" })
            local p = P(nil, { "This is ", strong, " text." })
            assert.are.equal("<p>This is <strong>important</strong> text.</p>", p:render())
        end)
    end)

    describe("A", function()
        it("should render an empty anchor tag", function()
            local a = A()
            assert.are.equal("<a></a>", a:render())
        end)

        it("should render an anchor tag with href and text", function()
            local a = A(nil, { "Google" }):addAttribute("href='https://google.com'")
            assert.are.equal("<a href='https://google.com'>Google</a>", a:render())
        end)

        it("should render an anchor tag with attributes and child elements", function()
            local span = Span(nil, { "Click me" })
            local a = A(nil, { span }):addAttribute("href='#top'")
            assert.are.equal("<a href='#top'><span>Click me</span></a>", a:render())
        end)
    end)

    describe("Html", function()
        it("should render a basic html structure", function()
            local html = Html(nil, {
                Head(nil, { Title(nil, { "Test Page" }) }),
                Body(nil, { P(nil, { "Hello" }) })
            })
            assert.are.equal("<html><head><title>Test Page</title></head><body><p>Hello</p></body></html>", html:render())
        end)

        it("should render html with attributes", function()
            local html = Html():addAttribute("lang='en'")
            assert.are.equal("<html lang='en'></html>", html:render())
        end)
    end)

    describe("Body", function()
        it("should render an empty body tag", function()
            local body = Body()
            assert.are.equal("<body></body>", body:render())
        end)

        it("should render a body with content", function()
            local body = Body(nil, { "Page content" })
            assert.are.equal("<body>Page content</body>", body:render())
        end)
    end)

    describe("Head", function()
        it("should render an empty head tag", function()
            local head = Head()
            assert.are.equal("<head></head>", head:render())
        end)

        it("should render a head with a title", function()
            local title = Title(nil, { "My Title" })
            local head = Head(nil, { title })
            assert.are.equal("<head><title>My Title</title></head>", head:render())
        end)
    end)

    describe("Title", function()
        it("should render an empty title tag", function()
            local title = Title()
            assert.are.equal("<title></title>", title:render())
        end)

        it("should render a title with text content", function()
            local title = Title(nil, { "Document Title" })
            assert.are.equal("<title>Document Title</title>", title:render())
        end)
    end)

    describe("Meta", function()
        it("should render a self-closing meta tag", function()
            local meta = Meta()
            assert.are.equal("<meta>", meta:render())
        end)

        it("should render a meta tag with attributes", function()
            local meta = Meta({ "charset='utf-8'" })
            assert.are.equal("<meta charset='utf-8'>", meta:render())
        end)
    end)

    describe("Link", function()
        it("should render a self-closing link tag", function()
            local link = Link()
            assert.are.equal("<link>", link:render())
        end)

        it("should render a link tag with attributes", function()
            local link = Link({ "rel='stylesheet'", "href='style.css'" })
            assert.are.equal("<link rel='stylesheet' href='style.css'>", link:render())
        end)
    end)

    describe("Script", function()
        it("should render an empty script tag", function()
            local script = Script()
            assert.are.equal("<script></script>", script:render())
        end)

        it("should render a script tag with src attribute", function()
            local script = Script():addAttribute("src='app.js'")
            assert.are.equal("<script src='app.js'></script>", script:render())
        end)

        it("should render a script tag with inline content", function()
            local script = Script(nil, { "alert('hello');" })
            assert.are.equal("<script>alert('hello');</script>", script:render())
        end)
    end)

    describe("H1", function()
        it("should render an empty h1 tag", function()
            local h1 = H1()
            assert.are.equal("<h1></h1>", h1:render())
        end)

        it("should render an h1 with text content", function()
            local h1 = H1(nil, { "Page Title" })
            assert.are.equal("<h1>Page Title</h1>", h1:render())
        end)
    end)

    describe("Header", function()
        it("should render an empty header tag", function()
            local header = Header()
            assert.are.equal("<header></header>", header:render())
        end)

        it("should render a header with an h1 child", function()
            local h1 = H1(nil, { "Welcome" })
            local header = Header(nil, { h1 })
            assert.are.equal("<header><h1>Welcome</h1></header>", header:render())
        end)
    end)

    describe("Main", function()
        it("should render an empty main tag", function()
            local main = Main()
            assert.are.equal("<main></main>", main:render())
        end)

        it("should render a main tag with content", function()
            local main = Main(nil, { "Main content here." })
            assert.are.equal("<main>Main content here.</main>", main:render())
        end)
    end)

    describe("Pre", function()
        it("should render an empty pre tag", function()
            local pre = Pre()
            assert.are.equal("<pre></pre>", pre:render())
        end)

        it("should render a pre tag with content", function()
            local pre = Pre(nil, { "Formatted\ntext" })
            assert.are.equal("<pre>Formatted\ntext</pre>", pre:render())
        end)
    end)

    describe("Input", function()
        it("should render a self-closing input tag", function()
            local input = Input()
            assert.are.equal("<input>", input:render())
        end)

        it("should render an input tag with attributes", function()
            local input = Input({ "type='text'", "value='hello'" })
            assert.are.equal("<input type='text' value='hello'>", input:render())
        end)
    end)

    describe("Br", function()
        it("should render a self-closing br tag", function()
            local br = Br()
            assert.are.equal("<br>", br:render())
        end)
    end)

    describe("Footer", function()
        it("should render an empty footer tag", function()
            local footer = Footer()
            assert.are.equal("<footer></footer>", footer:render())
        end)

        it("should render a footer with content", function()
            local p = P(nil, { "Copyright 2023" })
            local footer = Footer(nil, { p })
            assert.are.equal("<footer><p>Copyright 2023</p></footer>", footer:render())
        end)
    end)

    describe("Ins", function()
        it("should render an empty ins tag", function()
            local ins = Ins()
            assert.are.equal("<ins></ins>", ins:render())
        end)

        it("should render an ins tag with content", function()
            local ins = Ins(nil, { "Inserted text" })
            assert.are.equal("<ins>Inserted text</ins>", ins:render())
        end)

        it("should render an ins tag with a function as content", function()
            local ins = Ins(nil, function() return "dynamic content" end)
            assert.are.equal("<ins>dynamic content</ins>", ins:render())
        end)
    end)

    describe("Mark", function()
        it("should render an empty mark tag", function()
            local mark = Mark()
            assert.are.equal("<mark></mark>", mark:render())
        end)

        it("should render a mark tag with content", function()
            local mark = Mark(nil, { "Highlighted" })
            assert.are.equal("<mark>Highlighted</mark>", mark:render())
        end)

        it("should render a mark tag with a function as content", function()
            local mark = Mark(nil, function() return "computed value" end)
            assert.are.equal("<mark>computed value</mark>", mark:render())
        end)
    end)

    describe("Hr", function()
        it("should render a self-closing hr tag", function()
            local hr = Hr()
            assert.are.equal("<hr>", hr:render())
        end)
    end)

    describe("Article", function()
        it("should render an empty article tag", function()
            local article = Article()
            assert.are.equal("<article></article>", article:render())
        end)
        it("should render an article tag with content", function()
            local article = Article(nil, { "Article content" })
            assert.are.equal("<article>Article content</article>", article:render())
        end)
    end)

    describe("Aside", function()
        it("should render an empty aside tag", function()
            local aside = Aside()
            assert.are.equal("<aside></aside>", aside:render())
        end)
        it("should render an aside tag with content", function()
            local aside = Aside(nil, { "Aside content" })
            assert.are.equal("<aside>Aside content</aside>", aside:render())
        end)
    end)

    describe("Audio", function()
        it("should render an empty audio tag", function()
            local audio = Audio()
            assert.are.equal("<audio></audio>", audio:render())
        end)
        it("should render an audio tag with attributes", function()
            local audio = Audio({ "controls" })
            assert.are.equal("<audio controls></audio>", audio:render())
        end)
    end)

    describe("Blockquote", function()
        it("should render an empty blockquote tag", function()
            local blockquote = Blockquote()
            assert.are.equal("<blockquote></blockquote>", blockquote:render())
        end)
        it("should render a blockquote tag with content", function()
            local blockquote = Blockquote(nil, { "Quoted text" })
            assert.are.equal("<blockquote>Quoted text</blockquote>", blockquote:render())
        end)
    end)

    describe("Button", function()
        it("should render an empty button tag", function()
            local button = Button()
            assert.are.equal("<button></button>", button:render())
        end)
        it("should render a button tag with content", function()
            local button = Button(nil, { "Click Me" })
            assert.are.equal("<button>Click Me</button>", button:render())
        end)
    end)

    describe("Caption", function()
        it("should render an empty caption tag", function()
            local caption = Caption()
            assert.are.equal("<caption></caption>", caption:render())
        end)
        it("should render a caption tag with content", function()
            local caption = Caption(nil, { "Table Caption" })
            assert.are.equal("<caption>Table Caption</caption>", caption:render())
        end)
    end)

    describe("Code", function()
        it("should render an empty code tag", function()
            local code = Code()
            assert.are.equal("<code></code>", code:render())
        end)
        it("should render a code tag with content", function()
            local code = Code(nil, { "local x = 1" })
            assert.are.equal("<code>local x = 1</code>", code:render())
        end)
    end)

    describe("Em", function()
        it("should render an empty em tag", function()
            local em = Em()
            assert.are.equal("<em></em>", em:render())
        end)
        it("should render an em tag with content", function()
            local em = Em(nil, { "Emphasized text" })
            assert.are.equal("<em>Emphasized text</em>", em:render())
        end)
    end)

    describe("Figcaption", function()
        it("should render an empty figcaption tag", function()
            local figcaption = Figcaption()
            assert.are.equal("<figcaption></figcaption>", figcaption:render())
        end)
        it("should render a figcaption tag with content", function()
            local figcaption = Figcaption(nil, { "Figure caption" })
            assert.are.equal("<figcaption>Figure caption</figcaption>", figcaption:render())
        end)
    end)

    describe("Figure", function()
        it("should render an empty figure tag", function()
            local figure = Figure()
            assert.are.equal("<figure></figure>", figure:render())
        end)
        it("should render a figure tag with content", function()
            local img = Img():addAttribute("src='img.png'")
            local figcaption = Figcaption(nil, { "An image" })
            local figure = Figure(nil, { img, figcaption })
            assert.are.equal("<figure><img src='img.png'><figcaption>An image</figcaption></figure>", figure:render())
        end)
    end)

    describe("Form", function()
        it("should render an empty form tag", function()
            local form = Form()
            assert.are.equal("<form></form>", form:render())
        end)
        it("should render a form tag with content", function()
            local input = Input({ "type='text'" })
            local form = Form(nil, { input })
            assert.are.equal("<form><input type='text'></form>", form:render())
        end)
    end)

    describe("H2", function()
        it("should render an empty h2 tag", function()
            local h2 = H2()
            assert.are.equal("<h2></h2>", h2:render())
        end)
        it("should render an h2 tag with content", function()
            local h2 = H2(nil, { "Section Title" })
            assert.are.equal("<h2>Section Title</h2>", h2:render())
        end)
    end)

    describe("H3", function()
        it("should render an empty h3 tag", function()
            local h3 = H3()
            assert.are.equal("<h3></h3>", h3:render())
        end)
        it("should render an h3 tag with content", function()
            local h3 = H3(nil, { "Sub-section Title" })
            assert.are.equal("<h3>Sub-section Title</h3>", h3:render())
        end)
    end)

    describe("H4", function()
        it("should render an empty h4 tag", function()
            local h4 = H4()
            assert.are.equal("<h4></h4>", h4:render())
        end)
        it("should render an h4 tag with content", function()
            local h4 = H4(nil, { "Heading 4" })
            assert.are.equal("<h4>Heading 4</h4>", h4:render())
        end)
    end)

    describe("H5", function()
        it("should render an empty h5 tag", function()
            local h5 = H5()
            assert.are.equal("<h5></h5>", h5:render())
        end)
        it("should render an h5 tag with content", function()
            local h5 = H5(nil, { "Heading 5" })
            assert.are.equal("<h5>Heading 5</h5>", h5:render())
        end)
    end)

    describe("H6", function()
        it("should render an empty h6 tag", function()
            local h6 = H6()
            assert.are.equal("<h6></h6>", h6:render())
        end)
        it("should render an h6 tag with content", function()
            local h6 = H6(nil, { "Heading 6" })
            assert.are.equal("<h6>Heading 6</h6>", h6:render())
        end)
    end)

    describe("Img", function()
        it("should render a self-closing img tag", function()
            local img = Img()
            assert.are.equal("<img>", img:render())
        end)
        it("should render an img tag with attributes", function()
            local img = Img({ "src='test.jpg'", "alt='Test Image'" })
            assert.are.equal("<img src='test.jpg' alt='Test Image'>", img:render())
        end)
    end)

    describe("Label", function()
        it("should render an empty label tag", function()
            local label = Label()
            assert.are.equal("<label></label>", label:render())
        end)
        it("should render a label tag with content", function()
            local label = Label(nil, { "Username" })
            assert.are.equal("<label>Username</label>", label:render())
        end)
    end)

    describe("Li", function()
        it("should render an empty li tag", function()
            local li = Li()
            assert.are.equal("<li></li>", li:render())
        end)
        it("should render an li tag with content", function()
            local li = Li(nil, { "List Item" })
            assert.are.equal("<li>List Item</li>", li:render())
        end)
    end)

    describe("Nav", function()
        it("should render an empty nav tag", function()
            local nav = Nav()
            assert.are.equal("<nav></nav>", nav:render())
        end)
        it("should render a nav tag with content", function()
            local ul = Ul(nil, { Li(nil, { A(nil, { "Home" }):addAttribute("href='/'") }) })
            local nav = Nav(nil, { ul })
            assert.are.equal("<nav><ul><li><a href='/'>Home</a></li></ul></nav>", nav:render())
        end)
    end)

    describe("Ol", function()
        it("should render an empty ol tag", function()
            local ol = Ol()
            assert.are.equal("<ol></ol>", ol:render())
        end)
        it("should render an ol tag with list items", function()
            local ol = Ol(nil, { Li(nil, { "Item 1" }), Li(nil, { "Item 2" }) })
            assert.are.equal("<ol><li>Item 1</li><li>Item 2</li></ol>", ol:render())
        end)
    end)

    describe("Option", function()
        it("should render an empty option tag", function()
            local option = Option()
            assert.are.equal("<option></option>", option:render())
        end)
        it("should render an option tag with content and value", function()
            local option = Option(nil, { "Option 1" }):addAttribute("value='1'")
            assert.are.equal("<option value='1'>Option 1</option>", option:render())
        end)
    end)

    describe("Section", function()
        it("should render an empty section tag", function()
            local section = Section()
            assert.are.equal("<section></section>", section:render())
        end)
        it("should render a section tag with content", function()
            local section = Section(nil, { H2(nil, { "About Us" }), P(nil, { "Some text." }) })
            assert.are.equal("<section><h2>About Us</h2><p>Some text.</p></section>", section:render())
        end)
    end)

    describe("Select", function()
        it("should render an empty select tag", function()
            local select = Select()
            assert.are.equal("<select></select>", select:render())
        end)
        it("should render a select tag with options", function()
            local select = Select(nil, {
                Option({ "value='1'" }, { "One" }),
                Option({ "value='2'" }, { "Two" })
            })
            assert.are.equal("<select><option value='1'>One</option><option value='2'>Two</option></select>",
                select:render())
        end)
    end)

    describe("Span", function()
        it("should render an empty span tag", function()
            local span = Span()
            assert.are.equal("<span></span>", span:render())
        end)
        it("should render a span tag with content", function()
            local span = Span(nil, { "Inline text" })
            assert.are.equal("<span>Inline text</span>", span:render())
        end)
    end)

    describe("Strong", function()
        it("should render an empty strong tag", function()
            local strong = Strong()
            assert.are.equal("<strong></strong>", strong:render())
        end)
        it("should render a strong tag with content", function()
            local strong = Strong(nil, { "Bold text" })
            assert.are.equal("<strong>Bold text</strong>", strong:render())
        end)
    end)

    describe("Table", function()
        it("should render an empty table tag", function()
            local table_tag = Table()
            assert.are.equal("<table></table>", table_tag:render())
        end)
        it("should render a table tag with a caption", function()
            local table_tag = Table(nil, { Caption(nil, { "My Table" }) })
            assert.are.equal("<table><caption>My Table</caption></table>", table_tag:render())
        end)
    end)

    describe("Tbody", function()
        it("should render an empty tbody tag", function()
            local tbody = Tbody()
            assert.are.equal("<tbody></tbody>", tbody:render())
        end)
        it("should render a tbody tag with content", function()
            local tbody = Tbody(nil, { Tr(nil, { Td(nil, { "Cell" }) }) })
            assert.are.equal("<tbody><tr><td>Cell</td></tr></tbody>", tbody:render())
        end)
    end)

    describe("Td", function()
        it("should render an empty td tag", function()
            local td = Td()
            assert.are.equal("<td></td>", td:render())
        end)
        it("should render a td tag with content", function()
            local td = Td(nil, { "Data Cell" })
            assert.are.equal("<td>Data Cell</td>", td:render())
        end)
    end)

    describe("Textarea", function()
        it("should render an empty textarea tag", function()
            local textarea = Textarea()
            assert.are.equal("<textarea></textarea>", textarea:render())
        end)
        it("should render a textarea tag with content", function()
            local textarea = Textarea(nil, { "Default text" })
            assert.are.equal("<textarea>Default text</textarea>", textarea:render())
        end)
    end)

    describe("Th", function()
        it("should render an empty th tag", function()
            local th = Th()
            assert.are.equal("<th></th>", th:render())
        end)
        it("should render a th tag with content", function()
            local th = Th(nil, { "Table Header" })
            assert.are.equal("<th>Table Header</th>", th:render())
        end)
    end)

    describe("Thead", function()
        it("should render an empty thead tag", function()
            local thead = Thead()
            assert.are.equal("<thead></thead>", thead:render())
        end)
        it("should render a thead tag with content", function()
            local thead = Thead(nil, { Tr(nil, { Th(nil, { "Header" }) }) })
            assert.are.equal("<thead><tr><th>Header</th></tr></thead>", thead:render())
        end)
    end)

    describe("Tr", function()
        it("should render an empty tr tag", function()
            local tr = Tr()
            assert.are.equal("<tr></tr>", tr:render())
        end)
        it("should render a tr tag with content", function()
            local tr = Tr(nil, { Td(nil, { "Cell 1" }), Td(nil, { "Cell 2" }) })
            assert.are.equal("<tr><td>Cell 1</td><td>Cell 2</td></tr>", tr:render())
        end)
    end)

    describe("Ul", function()
        it("should render an empty ul tag", function()
            local ul = Ul()
            assert.are.equal("<ul></ul>", ul:render())
        end)
        it("should render a ul tag with list items", function()
            local ul = Ul(nil, { Li(nil, { "Bullet 1" }), Li(nil, { "Bullet 2" }) })
            assert.are.equal("<ul><li>Bullet 1</li><li>Bullet 2</li></ul>", ul:render())
        end)
    end)

    describe("Video", function()
        it("should render an empty video tag", function()
            local video = Video()
            assert.are.equal("<video></video>", video:render())
        end)
        it("should render a video tag with attributes", function()
            local video = Video({ "src='movie.mp4'", "controls" })
            assert.are.equal("<video src='movie.mp4' controls></video>", video:render())
        end)
    end)
end)
